In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model


In [51]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [52]:
df.bedrooms

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [53]:
df.bedrooms.fillna(df.bedrooms.median())

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [54]:
df.bedrooms =  df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [55]:
#creating a object of linear regression model 

reg = linear_model.LinearRegression()



#fit the model 

#DV = dependent variable
#IDV = Independent varible

#reg.fit("IDV IDV IDV","DV")



reg.fit(df.drop("price",axis="columns"),df["price"])


LinearRegression()

In [56]:
#ans 
reg.predict([[3000,3,40]])

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [57]:
#explanations

#y = m1*area + m2*bedrooms + m3*age + b 


In [58]:
reg.coef_


array([  112.06244194, 23388.88007794, -3231.71790863])

In [59]:
#the value of
#m1 = 112.06244194
#m2 = 23388.88007794 
#m3 = -3231.71790863


In [60]:
reg.intercept_

221323.00186540408

In [61]:
#the value of b  = 221323.00186540408

#we want to predict the price of a house which size id 3000sqr ft area , 3  bedrooms, 40 year old 

#a/c to maths 
#y = m1*area + m2*bedrooms + m3*age + b 

112.06244194* 3000 + 23388.88007794 *3 + (-3231.71790863*40) + 221323.00186540408


498408.2515740241

In [69]:

#second predictions 


reg.predict([[2500,4,50]])

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([433448.73160085])